// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulutlohjvqoarzismnxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsdXRsb2hqdnFvYXJ6aXNtbnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDQ0ODgsImV4cCI6MjA2MjY4MDQ4OH0.x4RQJ1AKOQuLhjFlWxdoY7CgfED2pRnf-pyw16b-GaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);